### ISSUE TITLE
Bind to Atom Effects

### ISSUE THREAD

**Issue by anmonteiro** [bloodyowl/rescript-recoil#17]
0.1.1 includes [Atom Effects](https://recoiljs.org/docs/guides/atom-effects/) which look pretty cool. Shouldn't be too hard to bind to them.

**Comment by bloodyowl** [comment]
Started implementation here https://github.com/bloodyowl/reason-recoil/pull/18, I'll add some tests and release after that

**Comment by anmonteiro** [comment]
I left a few comments, let's continue the discussion there. Thanks for jumping on this!

**Comment by bloodyowl** [comment]
Released in v0.11.0. (note: I've renamed the project on npm as `rescript-recoil`)
