### ISSUE TITLE
Atom Effect onSet

### ISSUE THREAD

**Issue by happylinks** [bloodyowl/rescript-recoil#19]
Hey there,

I'm having issues using `onSet((~newValue, ~oldValue) => { Js.log(newValue)});`
Could it be that the binding is wrong? https://github.com/bloodyowl/rescript-recoil/blob/0d6b5183af1be0fd1cc455d49138c035f4bcc032/src/Recoil__Atom.res#L8

I think it should be `onSet: ((~newValue: 'value, ~oldValue: 'value) => unit) => unit,`?

I can make a PR but wanted to check first if I might be doing something wrong.

**Comment by happylinks** [comment]
Made a PR here: https://github.com/bloodyowl/rescript-recoil/pull/20
Tested it as well and it works for me :)

**Comment by bloodyowl** [comment]
Thanks a lot @happylinks! Published as `0.11.1` 🙂

**Comment by happylinks** [comment]
Thanks for merging, the effects bindings are great!
