### ISSUE TITLE
Applications under the /examples does not work because of "module": "es6"

### ISSUE THREAD

**Issue by entyo** [bloodyowl/rescript-recoil#22]
## Reproduction steps

1. `yarn install`
2. `yarn build`
3. `yarn examples`
4. Open `http://localhost:8000/Async.html` (or any other html files) in the browser
5. Get `/TodoList.bs:3 Uncaught SyntaxError: Cannot use import statement outside a module` in the browser console

## FYI

If I change `"module": "es6"` in the `bsconfig.json` to `"module": "commonjs"`, It works well. I think that it would nice if the /examples is separated to the other repository or other package.

**Comment by bloodyowl** [comment]
Thanks for the report!
