### ISSUE TITLE
question: why gitignore .bs.js files?

### ISSUE THREAD

**Issue by thomaszdxsn** [bloodyowl/rescript-recoil#28]
In another project like rescript-org, it keep .mjs files

**Comment by bloodyowl** [comment]
Hi 👋 

In general I prefer to only keep the source versioned, it avoids some merge conflicts.

In the specific case of this repository, most of the output would be empty files, so I don't think it brings a lot of value.

**Comment by thomaszdxsn** [comment]
thanks
