### ISSUE TITLE
Dealing with `DefaultValue`

### ISSUE THREAD

**Issue by barodeur** [bloodyowl/rescript-recoil#33]
As I had the opportunity to say in my recent pull request #32: Thanks for this really nice binding. IMO the Recoil API types are particularly complex and those bindings really helps 🙏

---

My question is regarding this special type `DefaultValue` that Recoil has and that appear to be ignored from this binding.
It's used in some some callbacks instead of passing a value.

For example the `set` callback of a selector can either receive a value or an instance of `DefaultValue`. `DefaultValue` is passed to the callback when the action dispatch is a reset instead of setting a new value.

From [recoil doc](https://recoiljs.org/docs/api-reference/core/selector):
```javascript
function selector<T>({
  key: string,

  get: ({
    get: GetRecoilValue,
    getCallback: GetCallback,
  }) => T | Promise<T> | RecoilValue<T>,

  set?: (
    {
      get: GetRecoilValue,
      set: SetRecoilState,
      reset: ResetRecoilState,
    },
    newValue: T | DefaultValue,
  ) => void,

  dangerouslyAllowMutability?: boolean,

  cachePolicy_UNSTABLE?: CachePolicy,
})
```

Note that `SetRecoilState` can also be used to set a value to a `DefaultValue` instance.

The common pattern to handle this special value in javascript is the following:

```javascript
import { atom, selector, DefaultValue } from "recoil" 

const atom = atom({ key: "Atom", default: 1 })
const plusOne = selector({
  key: "AtomPlusOne",
  get: ({ get }) => get(atom) + 1,
  set: ({ set }, newValue) =>
    newValue instanceof DefaultValue
      ? set(atom, newValue) // forward the reset action
      : set(atom, newValue - 1)
})
```

Because of this `T | DefaultValue` type, it seems difficult to create a zero-cost binding that handle the `DefaultValue` separately using maybe a rescript variant type.

I'm pretty new rescript binding, but I was thinking that if the library would use a type like the one bellow, it would make handling the default value slightly simpler.

```rescript
module PossiblyDefaultValue = {
  @unboxed
  type t<'value> = PossiblyDefaultValue('value)

  type defaultValue
  @module("recoil") external defaultValue_: defaultValue = "DefaultValue"

  let defaultValue = defaultValue_

  @warning("-27")
  let isDefaultValue: t<'value> => bool = action => %raw("action instanceof defaultValue")
}
```

Personally, I would probably prefer a "low-cost" binding that would use a proper variant like `option<'value>`, or a new custom variant type, but at least I think that my suggestion above could provide the building bricks to build my own low-cost variant.

Do you think @bloodyowl that is is worth considering adding such a `PossiblyDefaultValue.t<'value>` type? I'll be more than happy to make this my second contribution to the bindings. If you decide to keep the types as they are, I would also be happy to just write down a "Dealing with `DefaultValue`" section to the readme.

**Comment by bloodyowl** [comment]
Hi 👋 Thanks for the detailed report!

I think that adding an additional type with runtime here might be a bit too cumbersome for the most common use-cases. Here's what I think is the best compromise given the use-case: https://github.com/bloodyowl/rescript-recoil/pull/35/files

It lies a bit about the actual type in that case, but it seems like the solution with the least breaking change & the most acceptable DX.

How does this look to you?

**Comment by barodeur** [comment]
Your proposed solution in #35 looks great as it introduces no breaking changes 👍

As of DX I would personally wrap this so I get a proper variant `DefaultValue | Value<'value>` but that's probably because my app uses Reset quite a lot.

Thanks for addressing this 🙏
